try:
    # código que pode causar um erro
    resultado = 10 / 0
except:
    # Códigp que trata o erro
    print("Ocorreu um erro durante a operação!")
